name: Run Telegram Bot
on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - run: pip install -r requirements.txt
      - run: python Musicbot.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
