name: Run Telegram Bot
on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |-
          # Botni ishga tushirish komandalari
